GET http://localhost:3002/ski-length-profiles

###

GET http://localhost:3002/ski-length-profiles/613b4a4c42dfe26ba405bdee

###

POST http://localhost:3002/ski-length-profiles
Content-Type: application/json

{
    "name": "Amazing Person",
    "height": 175,
    "age": 27,
    "skiLengthRange": {
        "min": 175,
        "max": 195
    }
}

###

DELETE http://localhost:3002/ski-length-profiles/613b6d13a23918e1de70ad95







