GET http://localhost:3002/ski-length-profiles

###

GET http://localhost:3002/ski-length-profiles/

###

POST http://localhost:3002/ski-length-profiles
Content-Type: application/json

{
    "name": "Amazing Person",
    "height": 175,
    "age": 27,
    "skiLengthRange": {
        "min": 175,
        "max": 195
    },
    "skiStyle": "Klassisk"
}

###

DELETE http://localhost:3002/ski-length-profiles/613df2b1701f67d1b9a82cd3












